server:
  port: '8080'
course-url: localhost:8085/api/v1
spring:
  application:
    name: ms-learning-cad
  data:
    mongodb:
      uri: mongodb://localhost:27017/ms-learning-cad
  kafka:
    producer:
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      group-id: topic-student
      retries-config: '10'
      acks-config: all
      bootstrap-servers: localhost:9092
    properties:
      schema:
        registry:
          url: http://127.0.0.1:8081
auto:
  create:
    topics:
      enable: 'true'
topic:
  name:
    producer: topic-student




